### ISSUE TITLE
Various build issues.

### ISSUE THREAD

**Issue by haampie** [SCOREC/omega_h#116]
When building with OMEGA_H_USE_CUDA (and cuda 11.8 or latest)

First I need to add

```diff
diff --git a/src/Omega_h_array.hpp b/src/Omega_h_array.hpp
index 30a94407..391a7d49 100644
--- a/src/Omega_h_array.hpp
+++ b/src/Omega_h_array.hpp
@@ -11,6 +11,7 @@
 #else
 #include <Omega_h_shared_alloc.hpp>
 #include <string>
+#include <memory>
 #endif
 
 namespace Omega_h {
```

but then it still doesn't build:

```
/tmp/omega-h/src/Omega_h_array_default.hpp(50): error: no operator "[]" matches these operands
            operand types are: const std::shared_ptr<Omega_h::I64> [ Omega_h::LO ]
          detected during instantiation of "const T &Omega_h::HostRead<T>::operator[](Omega_h::LO) const noexcept [with T=Omega_h::I64]" 
/tmp/omega-h/src/Omega_h_array.cpp(383): here
```

at this point I gave up.

**Comment by cwsmith** [comment]
Thanks for reporting the issue.  What compiler and version of cuda were you building with?

**Comment by haampie** [comment]
See https://gitlab.spack.io/spack/spack/-/jobs/13375261 which has a docker reproducer:

```
git -C /path/to/spack fetch https://github.com/spack/spack.git pull/47433/head
spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/13375261/artifacts --autostart
```

**Comment by cwsmith** [comment]
I am able to reproduce the errors with Gcc 12.3.0 and CUDA 12.1.105.

**Comment by cwsmith** [comment]
@haampie The cuda build issue should be resolved now `master` as of [78c9873](https://github.com/SCOREC/omega_h/commit/78c9873c72da01a83e06a835bdd5bd276e863f38).

**Comment by haampie** [comment]
Thanks, could you submit a PR to spack with either a patch or a conflict? I guess smth like `conflicts("@x:y +cuda~kokkos")`, but I don't know the range of versions that was broken.

**Comment by cwsmith** [comment]
You're welcome.  Here is the PR:  https://github.com/spack/spack/pull/47473
