### ISSUE TITLE
Issue converting Simmetrix to Omega_h mesh

### ISSUE THREAD

**Issue by zhangchonglin** [SCOREC/omega_h#20]
Using the latest master branch code at commit: 466e470, I am having problem converting a `*.sms` file to `*.osh` file, following the instruction: https://github.com/SCOREC/pumi-pic/wiki/simmetrix-to-omegah-mesh-conversion. The short error message is as below:
```
k_gene_comp_case5_fix.eqd.smd 37kmesh.osh
tet=0, hex=0, wedge=0, pyramid=0
assertion !has_ents(ent_dim) failed at /lore/zhangc20/pumi-pic/omega_h/src/Omega_h_mesh.cpp +112
Aborted (core dumped)
```

The `*.sms` file was generated using `simmetrix-simmodsuite/16.0-210606dev`. Similarly, `meshsim2osh` was generated using the same version. The conversion was working fine with everything generated using `simmetrix-simmodsuite/15.0-200714-x7ycno2`.

The case to reproduce this: https://github.com/SCOREC/xgc1_data/tree/master/Cyclone_ITG/Cyclone_ITG_deltaf_37kmesh.

**Comment by joshia5** [comment]
Is this a 2d mesh? if so, is it made up of all triangles, or all 
quadrilaterals, or mixed?

**Comment by zhangchonglin** [comment]
It's a 2D mesh, made up of all triangles.

**Comment by joshia5** [comment]
ok, i'll take a look and get back to you

**Comment by zhangchonglin** [comment]
@joshia5: Thanks! Please take your time, I have old branch `cws/meshSimReader` working.

**Comment by joshia5** [comment]
The support for 2d mono-topology meshes was added in this commit: https://github.com/joshia5/omega_h/commit/c22556aaec50558c79426026ce83d11cd2557e11#diff-e912495150ff797bffb04f16627ffbca904562593569f04fed674d86e475fc1f

Merge to scorec/omegah coming soon..

**Comment by zhangchonglin** [comment]
Thanks! Let me know once it's merged to the `master` branch, I will test it then.

**Comment by joshia5** [comment]
that branch is still a work in progress but it's been a while since this issue was opened so
i am merging relevant commits in this pr https://github.com/SCOREC/omega_h/pull/27
