### ISSUE TITLE
Number of components in a mesh tag is more than INT8_MAX

### ISSUE THREAD

**Issue by zhangchonglin** [SCOREC/omega_h#24]
Copying the same issue from `XGCm` for better location.

When the number of components for a mesh tag exceeds `INT8_MAX`, which is `127`, it is problematic as this could often happen.

Simply inferring from the below `assert` (`OMEGA_H_CHECK`) statement, INT8_MAX seems to be the upper limit manually set currently for the number of components. From my understanding, it may not be a simple manual limit to change, and could be related to many other operations:

https://github.com/SCOREC/omega_h/blob/b4a92caded940053c204d48dba8f933a76d31766/src/Omega_h_mesh.cpp#L242-L267

**Comment by jacobmerson** [comment]
@zhangchonglin is this still a problem for you?

**Comment by zhangchonglin** [comment]
I think we can close this as long as we are not using more than `127` components for a mesh tag.

**Comment by zhangchonglin** [comment]
I think we are fine for now as this is mostly a visualization issue.
