### ISSUE TITLE
copy semantics of Mesh

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/omega_h#28]
Looking at the Mesh class I'm not entirely sure 
```
Omega_h::Mesh mesh_a;
mesh_b = mesh_a; // most data is shared via internal shared ptrs, but not all!

mesh_b.set_dim(1); // dim is integer so copied by value...mesh dim in a still default value
mesh_b.set_coords(new_coords); // coords are a tag and tags are shared between mesh instances with shared ptr! now both mesh_a and mesh_b have new coords!
```
Also, you can't assume that the values stored internally as shared_ptrs will be shared between instances because some items like `set_parents()` assign a new shared_ptr, so assigning new values in one instance won't affect the other one.

I suspect most people are passing the mesh via ptr or reference and aren't actually copying a mesh instance which is why we haven't hit the nasty bug/confusion that this will cause.

Since copy doesn't do what people expect I suggest either deprecating or deleting the copy constructor/assignment until we decide on the intended semantics and fix the class to consistently abide by those semantics.

**Comment by cwsmith** [comment]
@jacobmerson This looks like a good question/comment for Dan.  Would you mind posting this on issues page for the `sandialabs/Omega_h` fork?

**Comment by jacobmerson** [comment]
Sure will do.

**Comment by jacobmerson** [comment]
This has been fixed upstream. We can close this issue when we rebase on sandialabs version.

**Comment by jacobmerson** [comment]
upstream has been merged in.
