### ISSUE TITLE
get/set tags with Topo_type vs dimension (integer)

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/omega_h#30]
It seems that the storage/retrieval of tags with either a topology type or dimension does not work as one would expect.

That's because those tags are stored and queried based on how they were added either by topo type or dimension.

For example if a tag is requested of dimension 3 (region) it will not return the tags that were set on Tets, Hexes, etc.

**Comment by joshia5** [comment]
The storage/retrieval of tags for mixed meshes works based on topology type. It is not based on dimension.  Following are the enum associated with the topo types:

`
enum class Topo_type : int {
  vertex,
  edge,
  triangle,
  quadrilateral,
  tetrahedron,
  hexahedron,
  wedge,
  pyramid
};
`

**Comment by jacobmerson** [comment]
@joshia5  I understand that there is a different set of functions when using topo_type or the dimension. What I'm saying is that is very surprising from the API perspective. As a user the only way that you would know this is by reading the code.

Do you have a lot of users using mixed meshes? It would probably make sense to break the mixed mesh functionality into a separate class since the current state is two orthogonal ways of working with the data mashed into a single class.

If you have only a few internal users for that functionality making some changes may be feasible and I can propose something.

Just bringing stuff up as I find it that catches me up. I'm open to discussion here.

**Comment by joshia5** [comment]
sounds good.. afaik i  don't think I have active users right now for the mixed mesh. I am open to discussions on improving the api design

**Comment by cwsmith** [comment]
resolved with https://github.com/SCOREC/omega_h/pull/82
