### ISSUE TITLE
make rcField functions private

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/omega_h#31]
working through fixing some rcField tests as I merge sandialabs. I'm wondering if there is any reason why we shouldn't push all of the rcField functions to be private methods on the mesh class? If I understand correctly these functions are all there to have an internal cache of stored values of the reverse classification.

If this is correct, then we should make all those methods private and just have the `ask_revClass` etc. functions be exposed in the namespace.

**Comment by joshia5** [comment]
sounds reasonable. i'll see when i can get to it.

**Comment by jacobmerson** [comment]
I can make this change when I'm done doing the merge with sandialabs. I will submit a pull request and request your approval to make sure I'm not too zealous with hiding things.
