### ISSUE TITLE
Check if it's possible to add simmodsuite to the test matrix

### ISSUE THREAD

**Issue by joshia5** [SCOREC/omega_h#37]
To regression test the features enabled with simmodsuite = on
cc'ing @cwsmith , we've had this discussion before but it keeps getting away due to other things so making a note here

**Comment by cwsmith** [comment]
We can now support this with a self-hosted runner.

**Comment by cwsmith** [comment]
We are still getting this setup for other repos with simmetrix/gpu needs that github hosted runners don't support. 

I've reopened this so it stays on the todo list.

**Comment by cwsmith** [comment]
As of [0d83b20](https://github.com/SCOREC/omega_h/commit/0d83b205e8577a0d153aca8387cd7cd1771336c7) we can now run the simmetrix build on our self-hosted runner.  It has to be triggered manually to avoid building/running untrusted code on our runner.
