### ISSUE TITLE
describe: provide more tag info

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/omega_h#77]
In the `describe` tool, we should add the following info on each tag:
- number of entities with a given values (this would require additional user input: tag name and value)
- min and max across all processes
- type (int, bool, float, real, etc.)
- change ‘size per entity’ → ‘number of components’

**Comment by Angelyr** [comment]
I can start this soon.

**Comment by Angelyr** [comment]
I have the tool ready, but I need a clarification on printing number of entities:
1. Should I use std::cin for the input or arguments?
2. If I use std::cin should I also ask for the rank or sum all the ranks?
3. Also should I ask for dimension or sum all the dimensions?

**Comment by cwsmith** [comment]
Great.  Thank you.

1. Let's assume for now the user would run `describe` once just to see what fields exist and then additional times to extract field specific data (for now the number of entities with a given value).  For the additional runs they would append a tag name and value to the command line arguments.
2. Sum across all ranks.  We should only count 'owned' entities with the specified value.
3. Good question.  The dimension should also be provided by the user on the command line.
